[package]
name = "screeps-starter-rust"
version = "0.0.0"
authors = []

[dependencies]
stdweb = "0.4"
log = "0.4"
fern = "0.5"
screeps-game-api = "0.3"
typetag = "0.1"
serde_json = "1"
serde_derive = "1"
serde = "1"

[profile.release]
panic = "abort"
opt-level = "s"
lto = true
