default_deploy_mode = "upload"

[upload]
username = "your username or email"
password = "your password"
branch = "default"
# prefix = "ptr"

# hostname = "screeps.com"
# ssl = true
# port = 443

# hostname = "localhost"
# ssl = false
# port = 21025

# for full syntax, see
# https://github.com/rustyscreeps/screeps-game-api/blob/master/screeps-defaults.toml
